spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update  # ?????create  ???update?????????????
      show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qol
    hikari:
      username: root
      password: root



